---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mineur-services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mineur-services
  template:
    metadata:
      labels:
        app: mineur-services
    spec:
      containers:
      - name: mineur-services
        image: 090380/mineur-services:1.00
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mineur-services
  labels:
    app: mineur-services
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 31010
  selector:
    app: mineur-services